worker_processes auto; // Se ajusta según las necesidades del servidor

events {
    worker_connections 1024; // cada proceso puede a tender a 1024 usuarios simultáneamente
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _; // Acepta cualquier nombre del dominio
        root /var/www/html/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string; // Redirige a index.php si no se encuentra el archivo o directorio solicitado
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; //Nginx no ejecuta php directamente, sino que lo pasa a un proceso de PHP-FPM
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all; // Deniega el acceso a archivos .htaccess por razones de seguridad
        }
    }
}
