[supervisord]
nodaemon=true
logfile=/dev/null //Super visor es el jefe de los procesos, lo ponemos en primer plano para que docker sepa que esta vivo
logfile_maxbytes=0

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/dev/stdout // Se  le dice al supervidor que inicie el php-fpm automaticamente
stdout_logfile_maxbytes=0  //  y que si se cae o hay algun error lo vuelva a levantar sin intervención manual
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout // El parametro "daemon off;" es necesario para que nginx se ejecute en primer plano,
stdout_logfile_maxbytes=0  // lo que permite a supervisord monitorear su estado y reiniciarlo si es necesario
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
