[supervisord]
nodaemon=true
logfile=/dev/null ; Supervisor es el jefe de los procesos, lo ponemos en primer plano para que Docker sepa que está vivo
logfile_maxbytes=0

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/dev/stdout ; Se le dice al supervisor que inicie el php-fpm automáticamente
stdout_logfile_maxbytes=0  ; y que si se cae o hay algún error lo vuelva a levantar sin intervención manual
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout ; El parámetro "daemon off;" es necesario para que nginx se ejecute en primer plano,
stdout_logfile_maxbytes=0  ; lo que permite a supervisord monitorear su estado y reiniciarlo si es necesario
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
